name: Vercel Preview Deployment
# environment variables
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
on:
  # when events that trigger CI/CD pipelines
  push:
    # filter only main branch will NOT happen for the CI/CD
    branches-ignore:
      - main
jobs:
  # one job at the moment for production at vercel
  Deploy-Preview:
    runs-on: ubuntu-latest

    # run the steps in terminal
    steps:
      - uses: actions/checkout@v3
      - name: Install Vercel CLI
        run: npm install --global vercel@latest
      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}
      - name: Build Project Artifacts
        run: vercel build --token=${{ secrets.VERCEL_TOKEN }}
      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }}
